version: '3.5'
services:
  selenoid:
    image: "aerokube/selenoid:1.10.7"
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - ".:/etc/selenoid" # path to browser.json
      - "/var/run/docker.sock:/var/run/docker.sock" # system properties
      - "E:\\OneDrive\\Documents\\demo\\build\\reports\\video:/opt/selenoid/video" # path to video
      - "./build/reports/logs/:/opt/selenoid/logs/" # path to log
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=E:\\OneDrive\\Documents\\demo\\build\\reports\\video"
    command: [ "-conf", "/etc/selenoid/browsers.json", # path to browser.json in container
               "-video-output-dir", "/opt/selenoid/video/", # path to video in container
               "-log-output-dir", "/opt/selenoid/logs", "-capture-driver-logs", # path to log in container
               "-container-network", "automation_default" ] # set network
    networks:
      - default

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    networks:
      - default

networks:
  default:
    name: automation_default



